#Makefile generico para cualquier programa

#Ejemplo: Ejemplo.o
#ld -o Instrucciones Instrucciones.o

#Ejemplo.o: Ejemplo.s
#as -g -o Ejemplo.o Ejemplo.s

#limpiar:
#rm Ejemplo Ejemplo.o


Ejemplo: 
  g++ Ejemplo.s -g -o Ejemplo
Run: 
  ./Ejemplo
gdbRun:
  gdb Ejemplo
Limpiar:
  rm Ejemplo
